spring:
  flyway:
    enabled: false
  datasource:
    url: ${DB_URL}
    port: ${DB_PORT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    default-models-expand-depth: 2
    default-models-rendering: model
  show-actuator: false
  packages-to-scan: com.example.tasks.controller

  paths-to-match: /tasks/**
